/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoprogra2;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import static proyectoprogra2.JDialogGestionChoferes.ListaChofe;
import static proyectoprogra2.JDialogGestionViajes.ListaGesVia;





/**
 *
 * @author jerem
 */
public class JDialogVentaTicket extends javax.swing.JDialog {
 DefaultComboBoxModel modelIdRuta = new DefaultComboBoxModel();
    ArrayList<VentaTicket>lista = new ArrayList<>();
    ArrayList<VentaTicket>listaTxt = new ArrayList<>();
    ArrayList<GestionViajes>ListaGesVia = new ArrayList<>();
    ArrayList<GestionViajes>listaTxtViaje = new ArrayList<>();
    String IdViaje;
    String PlacaBus;
    String CedulaChofer;
    String IdRuta;
    String Fecha;
    String Hora;
    int CantidadTickets;

    public JDialogVentaTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarDatosTxt();
        cargarDatosTxtViajes();
        readDataTable();
        String viaje [] = new String[ListaGesVia.size()];
        
        for(int i = 0; i< ListaGesVia.size() ; i++)
        {
          viaje[i] = ListaGesVia.get(i).getIdViaje();
        }
        JCBoxIdViaje.setModel(new javax.swing.DefaultComboBoxModel<>(viaje));
        JCBoxIdViaje.setSelectedIndex(-1);
        
        
         JTblVentaTicket.addMouseListener( new MouseAdapter()
            {
                DefaultTableModel model = new DefaultTableModel();
                @Override
                public void mouseClicked(MouseEvent e)
                    {
                    int i = JTblVentaTicket.getSelectedRow();
                    IdViaje = JTblVentaTicket.getValueAt(i, 0).toString();
                    CantidadTickets = Integer.parseInt(JTblVentaTicket.getValueAt(i, 1).toString());
                    }
                
                }
                  );
    }
    
    public void LimpiarCasillas()
     {
     TxtCantidadTickets.setText("");
     TxtCantidadTickets.setEditable(true);
     JCBoxIdViaje.setSelectedItem(null);
     BtnComprar.setEnabled(true);
     
     }
     /**
      * updateTxt
      * Este metodo va a guardar la información en el txt
      */
     public void  updateTxt()
     {
         ContextTXTVentaTicket.Guardardatos(lista);
     
         
     }
     /**
      * cargarDatosTxt
      * Este metodo agarra la información del txt 
      */
     public void cargarDatosTxt()
     {
         listaTxt = ContextTXTVentaTicket.LeerDatos();
         lista = listaTxt;
     
     }
     /**
      * cargarDatosTxtViajes
      * Este metodo agarra la información del txt de los viajes
      */
     public void cargarDatosTxtViajes()
     {
         listaTxtViaje = ContextTXTGestionViajes.LeerDatos();
         ListaGesVia = listaTxtViaje;
     }
     /**
      * readDataTable
      * Este metodo añadira los datos a la tabla
      */
    public void readDataTable()
     {
     
     String matriz [][] = new String[lista.size()][2];
        
     for(int i = 0; i< lista.size() ; i++)
        {
            matriz[i][0]= lista.get(i).getIdViaje();
            matriz[i][1]= String.valueOf(lista.get(i).getCantidadTickets());
        }
        JTblVentaTicket.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"Id Viaje","Tickets Vendidos"}));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnComprar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        JLblEdit = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JCBoxIdViaje = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TxtCantidadTickets = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblVentaTicket = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComprar.setText("Comprar");
        BtnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComprarMouseClicked(evt);
            }
        });
        jPanel2.add(BtnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 57, 84, -1));

        BtnActualizar.setText("Actualizar");
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 57, 84, -1));

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 57, 84, -1));

        BtnEditar.setText("Editar");
        BtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarMouseClicked(evt);
            }
        });
        jPanel2.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 57, -1, -1));

        JLblEdit.setText("........................................................");
        jPanel2.add(JLblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 20, 333, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 390, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID del viaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 59, 77, -1));

        JCBoxIdViaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(JCBoxIdViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 81, 91, -1));

        jLabel2.setText("Cantidad de Tickets:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 142, 120, -1));
        jPanel1.add(TxtCantidadTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 164, 120, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTblVentaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Viaje", "Tickets Vendidos"
            }
        ));
        JTblVentaTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblVentaTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTblVentaTicket);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 389, 446));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 410, 500));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void confirmarDatosViaje(){
        
        for (int i = 0; i < ListaGesVia.size() ; i++) {
            if(JCBoxIdViaje.getSelectedItem().toString().equals(ListaGesVia.get(i).getIdViaje()))
            {
                PlacaBus = ListaGesVia.get(i).getPlacaBus();
                CedulaChofer = ListaGesVia.get(i).getCedulaChofer();
                IdRuta = ListaGesVia.get(i).getIdRuta();
                Fecha = ListaGesVia.get(i).getFecha();
                Hora = ListaGesVia.get(i).getHora();
            
            }
        }
    }
    /**
     * 
     * @return verificarViaje
     * verifica que exista ese dato adentro del sistema
     */
    public boolean verificarViaje()
     {
         
        boolean var1 = false;
        cargarDatosTxt();
        for (int i = 0; i < lista.size() ; i++) 
        {
           
          if(JCBoxIdViaje.getSelectedItem().toString().equals(lista.get(i).getIdViaje()))
          {
             var1 = true;
          }
        }
         
         
         
     return var1;
     
     }
    private void JTblVentaTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblVentaTicketMouseClicked
   
        
    }//GEN-LAST:event_JTblVentaTicketMouseClicked

    private void BtnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComprarMouseClicked
        // TODO add your handling code here:
        int vari;
        if(verificarViaje()==false & !JCBoxIdViaje.getSelectedItem().equals("") & !TxtCantidadTickets.getText().isEmpty())
        {
            confirmarDatosViaje();           

            
          //  VentaTicket vt = new VentaTicket(JCBoxIdViaje.getSelectedItem().toString(),PlacaBus,CedulaChofer,IdRuta,Fecha,Hora,Integer.parseInt(TxtCantidadTickets.getText()));
          //  lista.add(vt);
            updateTxt();
            LimpiarCasillas();
            readDataTable();      
       }
        if (verificarViaje()==true & !TxtCantidadTickets.getText().isEmpty())
          { 
            //cantidadTiquetes = cantidadTiquetes + Integer.parseInt(txtTiquetes.getText());
            for (int j = 0; j < lista.size() ; j++) 
            { 
              if(JCBoxIdViaje.getSelectedItem().toString().equals(lista.get(j).getIdViaje())){
              vari = j;
              lista.get(vari).setCantidadTickets(lista.get(vari).getCantidadTickets() + Integer.parseInt(TxtCantidadTickets.getText()));
              }  
            }
            updateTxt();
            LimpiarCasillas();
            readDataTable();     
          }
        else
        {
          
         if (JCBoxIdViaje.getSelectedIndex() == -1)
          { 
              JOptionPane.showMessageDialog(null, "El campo ID de Viaje se encuentra vacio");
          }
           if(TxtCantidadTickets.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Por favor ingrese la cantidad de tickets que desea comprar");
            }
          
        }
    }//GEN-LAST:event_BtnComprarMouseClicked

    private void BtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseClicked
        // TODO add your handling code here:
        JCBoxIdViaje.setSelectedItem(IdViaje);
        TxtCantidadTickets.setText(String.valueOf(CantidadTickets));
        BtnComprar.setEnabled(false);
        JLblEdit.setText("Presione Actualizar una vez los datos sean actualizados");
    }//GEN-LAST:event_BtnEditarMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
        for (int j = 0; j < lista.size() ; j++) 
        {
          if(IdViaje.equals(lista.get(j).getIdViaje()))
          {    
              
              lista.get(j).setIdViaje(JCBoxIdViaje.getSelectedItem().toString());
              //confirmarDatosViaje();
              lista.get(j).setCantidadTickets(Integer.parseInt(TxtCantidadTickets.getText()));
              System.out.println(lista.get(j).getIdViaje());   
              //String idViajes, String placaBus, String cedulaChofer, String idRuta, String fecha, String hora,int cantidadTiquetes
                 
          }
        }
            
        
        readDataTable();
        LimpiarCasillas();
        updateTxt();
        JLblEdit.setText("");
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < lista.size(); i++) 
        {
            if(IdViaje.equals(lista.get(i).getIdViaje()))
            {
                lista.remove(i);
            
            }
        }
        
        readDataTable();
        updateTxt();
        LimpiarCasillas();
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed

 for (int i = 0; i < 10; i++) {

            if (listaTxtViaje.get(i).getIdViaje().equals(CantidadTickets)) {

           
           //     listaTxtViaje.get(i).setCantidadTickets(Integer.parseInt(TxtCantidadTickets.getText()));
                listaTxtViaje.get(i).setIdViaje((String) JCBoxIdViaje.getSelectedItem());
               

                ContextTXTVentaTicket.Guardardatos(listaTxtViaje);
                LimpiarCasillas();
                readDataTable();
            }

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed

        for (int i = 0; i < listaTxtViaje.size(); i++) {
            if (listaTxtViaje.get(i).getIdViaje().equals(CantidadTickets)) {
                listaTxtViaje.remove(i);
                ContextTXTVentaTicket.Guardardatos(listaTxtViaje);
                LimpiarCasillas();
                readDataTable();
            }

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogVentaTicket dialog = new JDialogVentaTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JComboBox<String> JCBoxIdViaje;
    private javax.swing.JLabel JLblEdit;
    private javax.swing.JTable JTblVentaTicket;
    private javax.swing.JTextField TxtCantidadTickets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
