/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoprogra2;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;





/**
 *
 * @author jerem
 */
public final class JDialogVentaTicket extends javax.swing.JDialog {
 DefaultComboBoxModel modelIdViaje = new DefaultComboBoxModel();
    ArrayList<VentaTicket>lista = new ArrayList<>();
    ArrayList<VentaTicket>listaTxt = new ArrayList<>();
    ArrayList<GestionViajes>ListaGesVia = new ArrayList<>();
    ArrayList<GestionViajes>listaTxtViaje = new ArrayList<>();
    String IdViaje;
    String PlacaBus;
    String CedulaChofer;
    String IdRuta;
    String Fecha;
    String Hora;
    String CantidadTickets;

    public JDialogVentaTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarData();
        CargarDatosIdViaje();
        cargarDataIDViajeComboBox();
        cargarDatosTxt();
        cargarDatosTxtViajes();
        readDataTable();
        String viaje [] = new String[ListaGesVia.size()];
        
        for(int i = 0; i< ListaGesVia.size() ; i++)
        {
          viaje[i] = ListaGesVia.get(i).getIdViaje();
        }
        CmbIdViaje.setModel(new javax.swing.DefaultComboBoxModel<>(viaje));
        CmbIdViaje.setSelectedIndex(-1);
        
        
         JTblVentaTicket.addMouseListener( new MouseAdapter()
            {
                DefaultTableModel model = new DefaultTableModel();
                @Override
                public void mouseClicked(MouseEvent e)
                    {
                    int i = JTblVentaTicket.getSelectedRow();
                    IdViaje = JTblVentaTicket.getValueAt(i, 0).toString();
                    CantidadTickets = JTblVentaTicket.getValueAt(i, 1).toString();
                     
                    }
                
                }
                  );
    }
    
    public void LimpiarCasillas()
     {
     TxtCantidadTickets.setText("");
     TxtCantidadTickets.setEditable(true);
     CmbIdViaje.setSelectedItem(null);
     BtnComprar.setEnabled(true);
     
     }
     /**
      * updateTxt
      * Este metodo va a guardar la información en el txt
      */
     public void  updateTxt()
     {
         ContextTXTVentaTicket.Guardardatos(lista);
     
         
     }
     /**
      * cargarDatosTxt
      * Este metodo agarra la información del txt 
      */
     public void cargarDatosTxt()
     {
         listaTxt = ContextTXTVentaTicket.LeerDatos();
         lista = listaTxt;
     
     }
     /**
      * cargarDatosTxtViajes
      * Este metodo agarra la información del txt de los viajes
      */
     public void cargarDatosTxtViajes()
     {
         listaTxtViaje = ContextTXTGestionViajes.LeerDatos();
         ListaGesVia = listaTxtViaje;
     }
     /**
      * readDataTable
      * Este metodo añadira los datos a la tabla
      */
    public void readDataTable()
     {
     
     String matriz [][] = new String[lista.size()][2];
        
     for(int i = 0; i< lista.size() ; i++)
        {
            matriz[i][0]= lista.get(i).getIdViaje();
            matriz[i][1]= String.valueOf(lista.get(i).getCantidadTickets());
        }
        JTblVentaTicket.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"Id Viaje","Tickets Vendidos"}));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CmbIdViaje = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TxtCantidadTickets = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnComprar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        JLblEdit = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblVentaTicket = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(243, 249, 249));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 249, 249));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 88, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID del viaje:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, -1));

        CmbIdViaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CmbIdViaje.setModel(modelIdViaje);
        jPanel1.add(CmbIdViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 88, 96));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cantidad de Tickets:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 220, -1));
        jPanel1.add(TxtCantidadTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 200, -1));

        jPanel2.setBackground(new java.awt.Color(243, 249, 249));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComprar.setBackground(new java.awt.Color(8, 31, 135));
        BtnComprar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnComprar.setForeground(new java.awt.Color(255, 255, 255));
        BtnComprar.setText("Comprar");
        BtnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnComprarMouseClicked(evt);
            }
        });
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, -1));

        BtnActualizar.setBackground(new java.awt.Color(8, 31, 135));
        BtnActualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnActualizarMouseClicked(evt);
            }
        });
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 100, -1));

        BtnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        BtnEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 100, -1));

        BtnEditar.setBackground(new java.awt.Color(8, 31, 135));
        BtnEditar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        BtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarMouseClicked(evt);
            }
        });
        jPanel2.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 400, -1));

        JLblEdit.setText("........................................................");
        jPanel1.add(JLblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 333, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 300));

        jPanel3.setBackground(new java.awt.Color(243, 249, 249));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTblVentaTicket.setAutoCreateRowSorter(true);
        JTblVentaTicket.setBackground(new java.awt.Color(243, 249, 249));
        JTblVentaTicket.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTblVentaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Viaje", "Tickets Vendidos"
            }
        ));
        JTblVentaTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblVentaTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTblVentaTicket);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 389, 446));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 410, 500));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void confirmarDatosViaje(){
        
        for (int i = 0; i < ListaGesVia.size() ; i++) {
            if(CmbIdViaje.getSelectedItem().toString().equals(ListaGesVia.get(i).getIdViaje()))
            {
                PlacaBus = ListaGesVia.get(i).getPlacaBus();
                CedulaChofer = ListaGesVia.get(i).getCedulaChofer();
                IdRuta = ListaGesVia.get(i).getIdRuta();
                Fecha = ListaGesVia.get(i).getFecha();
                Hora = ListaGesVia.get(i).getHora();
            
            }
        }
    }
    /**
     * 
     * @return verificarViaje
     * verifica que exista ese dato adentro del sistema
     */
    public boolean verificarViaje()
     {
         
        boolean var1 = false;
        cargarDatosTxt();
        for (int i = 0; i < lista.size() ; i++) 
        {
           
          if(CmbIdViaje.getSelectedItem().toString().equals(lista.get(i).getIdViaje()))
          {
             var1 = true;
          }
        }
         
         
         
     return var1;
     
     }
    private void JTblVentaTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblVentaTicketMouseClicked
  
       TxtCantidadTickets.setText(String.valueOf(CantidadTickets)); 
        BtnComprar.setEnabled(false);
        TxtCantidadTickets.setEnabled(false);   
        
    }//GEN-LAST:event_JTblVentaTicketMouseClicked

    private void BtnComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnComprarMouseClicked
       
        VentaTicket ven = new VentaTicket();
        ven.setIdViaje((String) CmbIdViaje.getSelectedItem());
        ven.setCantidadTickets(TxtCantidadTickets.getText());
        listaTxt.add(ven);
        ContextTXTVentaTicket.Guardardatos(listaTxt);
        LimpiarCasillas();
        showTable();
    }//GEN-LAST:event_BtnComprarMouseClicked

    private void BtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseClicked
        // TODO add your handling code here:
        CmbIdViaje.setSelectedItem(IdViaje);
        TxtCantidadTickets.setText(String.valueOf(CantidadTickets));
        BtnComprar.setEnabled(false);
        JLblEdit.setText("Presione Actualizar una vez los datos sean actualizados");
    }//GEN-LAST:event_BtnEditarMouseClicked

    private void BtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnActualizarMouseClicked
        // TODO add your handling code here:
        for (int j = 0; j < lista.size() ; j++) 
        {
          if(IdViaje.equals(lista.get(j).getIdViaje()))
          {    
              
              lista.get(j).setIdViaje(CmbIdViaje.getSelectedItem().toString());
              //confirmarDatosViaje();
              lista.get(j).setCantidadTickets(TxtCantidadTickets.getText());
              
              System.out.println(lista.get(j).getIdViaje());   
              //String idViajes, String placaBus, String cedulaChofer, String idRuta, String fecha, String hora,int cantidadTiquetes
                 
          }
        }
            
        
        readDataTable();
        LimpiarCasillas();
        updateTxt();
        JLblEdit.setText("");
    }//GEN-LAST:event_BtnActualizarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < lista.size(); i++) 
        {
            if(IdViaje.equals(lista.get(i).getIdViaje()))
            {
                lista.remove(i);
            
            }
        }
        
        readDataTable();
        updateTxt();
        LimpiarCasillas();
    }//GEN-LAST:event_BtnEliminarMouseClicked

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed

 for (int i = 0; i < 10; i++) {

            if (listaTxtViaje.get(i).getIdViaje().equals(CantidadTickets)) {

           
           //     listaTxtViaje.get(i).setCantidadTickets(Integer.parseInt(TxtCantidadTickets.getText()));
                listaTxtViaje.get(i).setIdViaje((String) CmbIdViaje.getSelectedItem());
               

                ContextTXTVentaTicket.Guardardatos(listaTxtViaje);
                LimpiarCasillas();
                readDataTable();
            }

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed

        for (int i = 0; i < listaTxtViaje.size(); i++) {
            if (listaTxtViaje.get(i).getIdViaje().equals(CantidadTickets)) {
                listaTxtViaje.remove(i);
                ContextTXTVentaTicket.Guardardatos(listaTxtViaje);
                LimpiarCasillas();
                readDataTable();
            }

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed

         VentaTicket ven = new VentaTicket();
         ven.setIdViaje((String) CmbIdViaje.getSelectedItem());
         ven.setCantidadTickets(TxtCantidadTickets.getText());
        
        listaTxt.add(ven);
        ContextTXTVentaTicket.Guardardatos(listaTxt);
        LimpiarCasillas();
        showTable();
        
        
    }//GEN-LAST:event_BtnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogVentaTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogVentaTicket dialog = new JDialogVentaTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JComboBox<String> CmbIdViaje;
    private javax.swing.JLabel JLblEdit;
    private javax.swing.JTable JTblVentaTicket;
    private javax.swing.JTextField TxtCantidadTickets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    public void cargarDataIDViajeComboBox() {
        String VecViaje[] = new String[ListaGesVia.size()];
        ListaGesVia = ContextTXTGestionViajes.LeerDatos();
        for (int i = 0; i < ListaGesVia.size(); i++) {
            VecViaje[i] = ListaGesVia.get(i).getIdViaje();
        }
        for (int i = 0; i < VecViaje.length; i++) {
            modelIdViaje.addElement(VecViaje[i]);
        }
        
        
    }

    
    public void CargarDatosIdViaje() {
        ListaGesVia = ContextTXTGestionViajes.LeerDatos();
    }

    private void showTable() {
        
          String vend[][] = new String[listaTxt.size()][2];

        for (int i = 0; i < listaTxt.size(); i++) {
            vend[i][0] = listaTxt.get(i).getIdViaje();
            vend[i][1] = listaTxt.get(i).getCantidadTickets();
           

    }
    }
    
    
     private void cargarData() {

        listaTxt = ContextTXTVentaTicket.LeerDatos();
    }
}
