/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoprogra2;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Sofia Murillo
 */
public class JDialogGestionFlotilla extends javax.swing.JDialog {
  static ArrayList<GestionFlotilla> gestionflotilla = new ArrayList<GestionFlotilla>();
  static String Placa;
static String CantidadPasajeros;
static String NombreBus;
static int VidaUtil;

  
    /**
     * Creates new form JDialogGestionFlotilla
     */
    public JDialogGestionFlotilla(java.awt.Frame parent, boolean modal) { 
        super(parent, modal);
        initComponents();
          cargarDatos();
        LeerTabla();
        setLocationRelativeTo(null);
        
          jTGestionFlotilla.addMouseListener(new MouseAdapter() {
            DefaultTableModel model = new DefaultTableModel();

            @Override
            public void mouseClicked(MouseEvent e) {
                int i = jTGestionFlotilla.getSelectedRow();
                    Placa = jTGestionFlotilla.getValueAt(i, 0).toString();
                CantidadPasajeros= jTGestionFlotilla.getValueAt(i, 1).toString();
                NombreBus = jTGestionFlotilla.getValueAt(i, 2).toString();
                VidaUtil = Integer.valueOf(jTGestionFlotilla.getValueAt(i, 3).toString());
            }
   });
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPlaca = new javax.swing.JLabel();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelPlaca1 = new javax.swing.JLabel();
        jLabelPlaca2 = new javax.swing.JLabel();
        jLabelNombrebus = new javax.swing.JLabel();
        jLabelCantidaPasajeros = new javax.swing.JLabel();
        jTextFieldCantidadPasajeros = new javax.swing.JTextField();
        jTextFieldVidautil = new javax.swing.JTextField();
        jTextFieldNombrebus = new javax.swing.JTextField();
        ButtonCrear = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        LbError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTGestionFlotilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelPlaca.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelPlaca.setForeground(new java.awt.Color(4, 88, 96));
        jLabelPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlaca.setText("Placa");

        jTextFieldPlaca.setText(" ");

        jLabelPlaca1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelPlaca1.setForeground(new java.awt.Color(4, 88, 96));
        jLabelPlaca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlaca1.setText("Vida Util (Km)");

        jLabelPlaca2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelPlaca2.setForeground(new java.awt.Color(4, 88, 96));
        jLabelPlaca2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelNombrebus.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelNombrebus.setForeground(new java.awt.Color(4, 88, 96));
        jLabelNombrebus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombrebus.setText("Nombre bus");

        jLabelCantidaPasajeros.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelCantidaPasajeros.setForeground(new java.awt.Color(4, 88, 96));
        jLabelCantidaPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidaPasajeros.setText("Cantidad Pasajeros");

        jTextFieldCantidadPasajeros.setText(" ");

        jTextFieldVidautil.setText(" ");

        jTextFieldNombrebus.setText(" ");

        ButtonCrear.setBackground(new java.awt.Color(0, 0, 205));
        ButtonCrear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCrear.setText("Crear");
        ButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearActionPerformed(evt);
            }
        });

        ButtonActualizar.setBackground(new java.awt.Color(0, 0, 205));
        ButtonActualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonEliminar.setBackground(new java.awt.Color(255, 0, 51));
        ButtonEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        LbError.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombrebus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCantidaPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LbError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonEliminar)
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addComponent(jLabelPlaca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldVidautil, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombrebus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldCantidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabelPlaca2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbError)
                .addGap(43, 43, 43)
                .addComponent(jLabelPlaca)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelCantidaPasajeros)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCantidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombrebus)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombrebus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPlaca1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldVidautil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCrear)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonEliminar))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabelPlaca2)
                    .addContainerGap(511, Short.MAX_VALUE)))
        );

        jTGestionFlotilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Cantidad Pasajeros", "Nombre", "Vida Util"
            }
        ));
        jTGestionFlotilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTGestionFlotillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTGestionFlotilla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearActionPerformed
       GestionFlotilla gestFlo = new  GestionFlotilla ();
        gestFlo.setPlaca(jTextPlaca.getText());
        gestFlo.setCantidadPasajeros(jTextFieldCantidadPasajeros.getText());
        gestFlo.setNombreBus(jTextFieldNombrebus.getText());
        gestFlo.setVidaUtil(Integer.parseInt(jTextFieldVidautil.getText()));
       

        gestionflotilla.add(gestFlo);
         ContextTXTGestionFlotilla.Guardardatos(gestionflotilla);
              LeerTabla();
                // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCrearActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
   for (int i = 0; i < 10; i++) {

            if (gestionflotilla.get(i).getPlaca().equals(Placa))
            {
              
//                
                gestionflotilla.get(i).setPlaca(jTextPlaca.getText());
                gestionflotilla.get(i).setCantidadPasajeros(jTextFieldCantidadPasajeros.getText());
                gestionflotilla.get(i).setNombreBus(jTextFieldNombrebus.getText());
                               gestionflotilla.get(i).setVidaUtil(Integer.parseInt(jTextFieldVidautil.getText()));
                
                ContextTXTGestionFlotilla.LeerDatos();
                 LeerTabla();

            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
 try {
            for (int i = 0; i < gestionflotilla.size(); i++) {
                if (gestionflotilla.get(i).getPlaca().equals(Placa)) {
                    gestionflotilla.remove(i);
                     ContextTXTGestionFlotilla.Guardardatos(gestionflotilla);
                    
                    LeerTabla();
                }

            }
        } catch (Exception e) {
            LbError.setText("Error al eliminar el profesor");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void jTGestionFlotillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTGestionFlotillaMouseClicked
        jTextPlaca.setText(Placa);
        jTextFieldCantidadPasajeros.setText(CantidadPasajeros);
        jTextFieldNombrebus.setText(NombreBus);
         jTextFieldVidautil.setText(String.valueOf(VidaUtil));
        ButtonCrear.setEnabled(false);
        jTextPlaca.setEnabled(false);

         
         
             // TODO add your handling code here:
    }//GEN-LAST:event_jTGestionFlotillaMouseClicked
 public void cargarDatos() {
        gestionflotilla = ContextTXTGestionFlotilla.LeerDatos();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGestionFlotilla dialog = new JDialogGestionFlotilla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public void LeerTabla() {

        String GesFlofMat[][] = new String[gestionflotilla.size()][8];

        for (int i = 0; i < gestionflotilla.size(); i++) {
            GesFlofMat[i][0] = gestionflotilla.get(i).getPlaca();
            GesFlofMat[i][1] = gestionflotilla.get(i).getCantidadPasajeros();
            GesFlofMat[i][2] = gestionflotilla.get(i).getNombreBus();
           GesFlofMat[i][6] = String.valueOf(gestionflotilla.get(i).getVidaUtil());
            
        }
        jTGestionFlotilla.setModel(new javax.swing.table.DefaultTableModel(GesFlofMat, new String[]{"Placa", "Nombre", "Cantidad de Pasajeros", " Nombre Bus", "Vida Util (Km)"}));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonCrear;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JLabel LbError;
    private javax.swing.JLabel jLabelCantidaPasajeros;
    private javax.swing.JLabel jLabelNombrebus;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlaca1;
    private javax.swing.JLabel jLabelPlaca2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTGestionFlotilla;
    private javax.swing.JTextField jTextFieldCantidadPasajeros;
    private javax.swing.JTextField jTextFieldNombrebus;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldVidautil;
    private javax.swing.JTextField jTextPlaca;
    // End of variables declaration//GEN-END:variables
}
