/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoprogra2;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import static proyectoprogra2.JDialogGestionChoferes.ListaChofe;
import static proyectoprogra2.JDialogGestionRutas.gestionrutas;

/**
 *
 * @author jeaus
 */
public class JDialogGestionViajes extends javax.swing.JDialog {
    
    
    DefaultComboBoxModel modelIdRuta = new DefaultComboBoxModel();
     DefaultComboBoxModel modelPlaBus = new DefaultComboBoxModel();
     DefaultComboBoxModel modelCeduChofe = new DefaultComboBoxModel();
    static ArrayList<GestionViajes> ListaGesVia = new ArrayList<GestionViajes>();
    String IDViaje;
    String PlacaBus;
    String CedulaChofer;
    String IDRuta;
    String Fecha;
    String Hora;


    /**
     * Creates new form JDialogGestionViajes
     */
    public JDialogGestionViajes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         cargarData();
        showTable();
        setLocationRelativeTo(null);
        TblGestionViaje.addMouseListener(new MouseAdapter() {
            DefaultTableModel model = new DefaultTableModel();
                
                  @Override
            public void mouseClicked(MouseEvent e) {
                int i = TblGestionViaje.getSelectedRow();
                IDViaje = TblGestionViaje.getValueAt(i, 0).toString();
                PlacaBus = TblGestionViaje.getValueAt(i, 1).toString();
                CedulaChofer = TblGestionViaje.getValueAt(i, 2).toString();
                IDRuta = TblGestionViaje.getValueAt(i, 3).toString();
                Fecha = TblGestionViaje.getValueAt(i, 4).toString();
                Hora = TblGestionViaje.getValueAt(i, 5).toString();
            }

        });
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CmbPlacaBus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TextIdViaje = new javax.swing.JTextField();
        CmbCedulaChofer = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CmbIdRuta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TextFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextHora = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        ButtonCrear = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonBorrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblGestionViaje = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 249, 249));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 88, 96));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID Viaje");

        CmbPlacaBus.setModel(modelPlaBus);
        CmbPlacaBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbPlacaBusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(4, 88, 96));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Placa Bus");

        CmbCedulaChofer.setModel(modelCeduChofe);
        CmbCedulaChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbCedulaChoferActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(4, 88, 96));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cedula Chofer");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(4, 88, 96));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID Ruta");

        CmbIdRuta.setModel(modelIdRuta);
        CmbIdRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbIdRutaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(4, 88, 96));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(4, 88, 96));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hora");

        ButtonCrear.setBackground(new java.awt.Color(0, 0, 255));
        ButtonCrear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCrear.setText("Crear");
        ButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCrearActionPerformed(evt);
            }
        });

        ButtonActualizar.setBackground(new java.awt.Color(0, 0, 255));
        ButtonActualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonBorrar.setBackground(new java.awt.Color(255, 0, 51));
        ButtonBorrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonBorrar.setText("Borrar");
        ButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonBorrar)
                .addGap(51, 51, 51))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCrear)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonBorrar))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmbPlacaBus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIdViaje)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmbCedulaChofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CmbIdRuta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFecha)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextHora))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIdViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CmbPlacaBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(CmbCedulaChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbIdRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(243, 249, 249));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        TblGestionViaje.setAutoCreateRowSorter(true);
        TblGestionViaje.setBackground(new java.awt.Color(243, 249, 249));
        TblGestionViaje.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TblGestionViaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TblGestionViaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Viaje", "Placa Bus", "Cedula Chofer", "ID Ruta", "Fecha", "Hora"
            }
        ));
        TblGestionViaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblGestionViajeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblGestionViaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(104, 104, 104))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCrearActionPerformed
        
        GestionViajes via = new GestionViajes();
        via.setIdViaje(TextIdViaje.getText());
        via.setFecha(TextFecha.getText());
        via.setHora(TextHora.getText());
      
        ListaGesVia.add(via);
        ContextTXTGestionChoferes.GuardarDatos(ListaGesVia);
        LimpiarCasillas();
        showTable();   
                            
        
        
    }//GEN-LAST:event_ButtonCrearActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        
        
        for (int i = 0; i < 10; i++) {

            if (ListaGesVia.get(i).getIdViaje().equals(IDViaje))
            {

                ListaGesVia.get(i).setIdViaje(TextIdViaje.getText());
                ListaGesVia.get(i).setPlacaBus(TextFecha.getText());
                ListaGesVia.get(i).setCedulaChofer(TextHora.getText());

                ContextTXTGestionRuta.Guardardatos(ListaGesVia);
                LimpiarCasillas();
                showTable();

            }

        }
    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBorrarActionPerformed
        
        for (int i = 0; i < ListaGesVia.size(); i++) {
                if (ListaGesVia.get(i).getIdViaje().equals(IDViaje)) {
                    ListaGesVia.remove(i);
                    ContextTXTGestionRuta.Guardardatos(ListaGesVia);
                    LimpiarCasillas();
                    showTable();
                }

            }  
    }//GEN-LAST:event_ButtonBorrarActionPerformed

    private void TblGestionViajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblGestionViajeMouseClicked
        
        TextIdViaje.setText(IDViaje);
        TextFecha.setText(Fecha);
        TextHora.setText(Hora);
        ButtonCrear.setEnabled(false);
        TextIdViaje.setEnabled(false);
    }//GEN-LAST:event_TblGestionViajeMouseClicked

    private void CmbPlacaBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbPlacaBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbPlacaBusActionPerformed

    private void CmbCedulaChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbCedulaChoferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbCedulaChoferActionPerformed

    private void CmbIdRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbIdRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbIdRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGestionViajes dialog = new JDialogGestionViajes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonBorrar;
    private javax.swing.JButton ButtonCrear;
    private javax.swing.JComboBox<String> CmbCedulaChofer;
    private javax.swing.JComboBox<String> CmbIdRuta;
    private javax.swing.JComboBox<String> CmbPlacaBus;
    private javax.swing.JTable TblGestionViaje;
    private javax.swing.JTextField TextFecha;
    private javax.swing.JTextField TextHora;
    private javax.swing.JTextField TextIdViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarData() {
        
        ListaGesVia = ContentTXTGestionViajes.LeerDatos();
    }

    private void showTable() {
        
         String chof[][] = new String[ListaGesVia.size()][6];

        for (int i = 0; i < ListaGesVia.size(); i++) {
            chof[i][0] = ListaGesVia.get(i).getIdViaje();
            chof[i][1] = ListaGesVia.get(i).getPlacaBus();
            chof[i][2] = ListaGesVia.get(i).getCedulaChofer();
            chof[i][3] = ListaGesVia.get(i).getIdRuta();
            chof[i][4] = ListaGesVia.get(i).getFecha();
            chof[i][5] = ListaGesVia.get(i).getHora();
           
        }
        TblGestionViaje.setModel(new javax.swing.table.DefaultTableModel(chof, new String[]{"ID Viaje", "Placa Bus", "Cedula Chofer", "ID Ruta", "Fecha", "Hora"}));

    }
    

    private void LimpiarCasillas() {
        
        TextIdViaje.setText("");
        TextFecha.setText("");
        TextHora.setText("");
        TextIdViaje.setEnabled(true);
        ButtonCrear.setEnabled(true);
    }
    
    
    
    
    public void cargarDatosPlacaBusComboBox()
    {

         String VecPlaca [] = new String[gestionflotilla.size()];
       gestionflotilla = ContextTXTGestionFlotilla.LeerDatos();
        for (int i = 0; i < gestionflotilla.size(); i++) 
        {
            VecPlaca[i] = gestionflotilla.get(i).getPlaca();
        }
         for (int i = 0; i < VecPlaca.length; i++)
             modelPlaBus.addElement(VecPlaca);
         }
    
    
    
    
     public void cargarDatosCedulaChoferComboBox()
    {
         String VecCedulaCh [] = new String[ListaChofe.size()];
       ListaChofe = ContextTXTGestionChoferes.LeerDatos();
        for (int i = 0; i < ListaChofe.size(); i++) 
        {
            VecCedulaCh[i] = ListaChofe.get(i).getCedula();
        }
        for (int i = 0; i < VecCedulaCh.length; i++)
        {
            modelCeduChofe.addElement(VecCedulaCh[i]);  
        }
    }
    
    
       public void cargarDatosIdRutaComboBox()
    {
         String VecRu [] = new String[gestionrutas.size()];
       gestionrutas = ContextTXTGestionRuta.LeerDatos();
        for (int i = 0; i < gestionrutas.size(); i++) 
        {
            VecRu[i] = gestionrutas.get(i).getRuta();
        }
        for (int i = 0; i < VecRu.length; i++)
        {
            modelIdRuta.addElement(VecRu[i]);  
        }
    }
    
    
    
    
    
}


