/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectoprogra2;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sofia Murillo
 */
public class JDialogGestionFlotilla extends javax.swing.JDialog {

    static ArrayList<GestionFlotilla> flo = new ArrayList<GestionFlotilla>();
    static String NumPlaca;
    static String CantidadPasajeros;
    static String NombreBus;
    static String VidaUtil;

    /**
     * Creates new form JDialogGestionFlotilla
     */
    public JDialogGestionFlotilla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarDatos();
        TablaContenido();
        setLocationRelativeTo(null);

        JtGestionFlotilla.addMouseListener(new MouseAdapter() {
            DefaultTableModel model = new DefaultTableModel();

            @Override
            public void mouseClicked(MouseEvent e) {
                int i = JtGestionFlotilla.getSelectedRow();
                NumPlaca = JtGestionFlotilla.getValueAt(i, 0).toString();
                CantidadPasajeros = JtGestionFlotilla.getValueAt(i, 1).toString();
                NombreBus = JtGestionFlotilla.getValueAt(i, 2).toString();
                VidaUtil = JtGestionFlotilla.getValueAt(i, 3).toString();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPlaca = new javax.swing.JLabel();
        TxtPlaca = new javax.swing.JTextField();
        jLabelPlaca1 = new javax.swing.JLabel();
        jLabelPlaca2 = new javax.swing.JLabel();
        jLabelNombrebus = new javax.swing.JLabel();
        jLabelCantidaPasajeros = new javax.swing.JLabel();
        TxtPasajeros = new javax.swing.JTextField();
        TxtVida = new javax.swing.JTextField();
        TxtBus = new javax.swing.JTextField();
        BtnCrear = new javax.swing.JButton();
        ButtonActualizar = new javax.swing.JButton();
        ButtonEliminar = new javax.swing.JButton();
        LbError = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        JLabelError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtGestionFlotilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 249, 249));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPlaca.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelPlaca.setForeground(new java.awt.Color(4, 88, 96));
        jLabelPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlaca.setText("Placa");

        TxtPlaca.setText(" ");

        jLabelPlaca1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelPlaca1.setForeground(new java.awt.Color(4, 88, 96));
        jLabelPlaca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPlaca1.setText("Vida Util (Km)");

        jLabelPlaca2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelPlaca2.setForeground(new java.awt.Color(4, 88, 96));
        jLabelPlaca2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelNombrebus.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelNombrebus.setForeground(new java.awt.Color(4, 88, 96));
        jLabelNombrebus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombrebus.setText("Nombre bus");

        jLabelCantidaPasajeros.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelCantidaPasajeros.setForeground(new java.awt.Color(4, 88, 96));
        jLabelCantidaPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidaPasajeros.setText("Cantidad Pasajeros");

        TxtPasajeros.setText(" ");

        TxtVida.setText(" ");

        TxtBus.setText(" ");

        BtnCrear.setBackground(new java.awt.Color(8, 31, 135));
        BtnCrear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnCrear.setForeground(new java.awt.Color(255, 255, 255));
        BtnCrear.setText("Crear");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearActionPerformed(evt);
            }
        });

        ButtonActualizar.setBackground(new java.awt.Color(8, 31, 135));
        ButtonActualizar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonActualizar.setText("Actualizar");
        ButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarActionPerformed(evt);
            }
        });

        ButtonEliminar.setBackground(new java.awt.Color(54, 86, 21));
        ButtonEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        LbError.setText(" ");

        BtnSalir.setBackground(new java.awt.Color(153, 0, 0));
        BtnSalir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombrebus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCantidaPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LbError, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JLabelError)
                                        .addGap(53, 53, 53))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlaca1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(ButtonEliminar)
                                .addGap(0, 13, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtVida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtBus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabelPlaca2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(49, 49, 49)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbError)
                    .addComponent(JLabelError))
                .addGap(43, 43, 43)
                .addComponent(jLabelPlaca)
                .addGap(18, 18, 18)
                .addComponent(TxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelCantidaPasajeros)
                .addGap(18, 18, 18)
                .addComponent(TxtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombrebus)
                .addGap(18, 18, 18)
                .addComponent(TxtBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPlaca1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCrear)
                    .addComponent(ButtonActualizar)
                    .addComponent(ButtonEliminar))
                .addGap(35, 35, 35)
                .addComponent(BtnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jLabelPlaca2)
                    .addContainerGap(511, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(243, 249, 249));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JtGestionFlotilla.setAutoCreateRowSorter(true);
        JtGestionFlotilla.setBackground(new java.awt.Color(243, 249, 249));
        JtGestionFlotilla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JtGestionFlotilla.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JtGestionFlotilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Placa", "Cantidad Pasajeros", "Nombre Bus", "Vida util"
            }
        ));
        JtGestionFlotilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JtGestionFlotillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JtGestionFlotilla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearActionPerformed
        GestionFlotilla gestFlo = new GestionFlotilla();
        gestFlo.setPlaca(TxtPlaca.getText());
        gestFlo.setCantidadPasajeros(TxtPasajeros.getText());
        gestFlo.setNombreBus(TxtBus.getText());
        gestFlo.setVidaUtil(TxtVida.getText());
        
        flo.add(gestFlo);
        ContextTXTGestionFlotilla.Guardardatos(flo);
        LimpiarCasillas();
        TablaContenido();
    }//GEN-LAST:event_BtnCrearActionPerformed

    private void ButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarActionPerformed
        
        for (int i = 0; i < 4; i++) {

            if (flo.get(i).getPlaca().equals(NumPlaca)) {
                
                flo.get(i).setPlaca(TxtPlaca.getText());
                flo.get(i).setCantidadPasajeros(TxtPasajeros.getText());
                flo.get(i).setNombreBus(TxtBus.getText());
                flo.get(i).setVidaUtil(TxtVida.getText());
                
                ContextTXTGestionFlotilla.Guardardatos(flo);
                LimpiarCasillas();
                TablaContenido();

            }
        }

    }//GEN-LAST:event_ButtonActualizarActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
        try {
            for (int i = 0; i < flo.size(); i++) {
                if (flo.get(i).getPlaca().equals(NumPlaca)) {
                    flo.remove(i);
                    ContextTXTGestionFlotilla.Guardardatos(flo);
                    LimpiarCasillas();
                    TablaContenido();
                }

            }
        } catch (Exception e) {
            JLabelError.setText("Error al eliminar la flotilla");

        }
    }//GEN-LAST:event_ButtonEliminarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        JFrameSISBUS sisbus = new JFrameSISBUS();
        sisbus.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void JtGestionFlotillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JtGestionFlotillaMouseClicked
        TxtPlaca.setText(NumPlaca);
        TxtPasajeros.setText(CantidadPasajeros);
        TxtBus.setText(NombreBus);
        TxtVida.setText(VidaUtil);
        BtnCrear.setEnabled(false);
        TxtPlaca.setEnabled(false);       
    }//GEN-LAST:event_JtGestionFlotillaMouseClicked

    private void cargarDatos() {
        flo = ContextTXTGestionFlotilla.LeerDatos();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogGestionFlotilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogGestionFlotilla dialog = new JDialogGestionFlotilla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void TablaContenido() {

        String flot[][] = new String[flo.size()][4];

        for (int i = 0; i < flo.size(); i++) {
            flot[i][0] = flo.get(i).getPlaca();
            flot[i][1] = flo.get(i).getCantidadPasajeros();
            flot[i][2] = flo.get(i).getNombreBus();
            flot[i][3] = flo.get(i).getVidaUtil();
        }
        JtGestionFlotilla.setModel(new javax.swing.table.DefaultTableModel(flot, new String[]{"Placa", "CantidadPasajeros", "NombreBus", " VidaUtil"}));

    } 

    private void LimpiarCasillas() {

        TxtPlaca.setText("");
        TxtPasajeros.setText("");
        TxtBus.setText("");
        TxtVida.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton ButtonActualizar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JLabel JLabelError;
    private javax.swing.JTable JtGestionFlotilla;
    private javax.swing.JLabel LbError;
    private javax.swing.JTextField TxtBus;
    private javax.swing.JTextField TxtPasajeros;
    private javax.swing.JTextField TxtPlaca;
    private javax.swing.JTextField TxtVida;
    private javax.swing.JLabel jLabelCantidaPasajeros;
    private javax.swing.JLabel jLabelNombrebus;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlaca1;
    private javax.swing.JLabel jLabelPlaca2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
