/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra2;

import static proyectoprogra2.JDialogGestionViajes.ListaGesVia;

/**
 *
 * @author rosbinvasquez
 */
public class JFrameSISBUS extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSISBUS
     */
    public JFrameSISBUS() {
        initComponents();
        ShowTableGestionViaje();
        Cargardata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BtnGestionFlotilla = new javax.swing.JButton();
        BtnGestionRutas = new javax.swing.JButton();
        BtnGestionChoferes = new javax.swing.JButton();
        BtnAdministrador = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        BtnIterar = new javax.swing.JButton();
        BtnGestionViajes = new javax.swing.JButton();
        BtnVentaTickets = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableGeneral = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(179, 222, 223));

        jPanel2.setBackground(new java.awt.Color(243, 249, 249));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/LogoBusP.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("SISTEMAS DE BUSES");

        BtnGestionFlotilla.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnGestionFlotilla.setForeground(new java.awt.Color(0, 102, 102));
        BtnGestionFlotilla.setText("Gestionar Flotilla");
        BtnGestionFlotilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BtnGestionFlotilla.setContentAreaFilled(false);
        BtnGestionFlotilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionFlotillaActionPerformed(evt);
            }
        });

        BtnGestionRutas.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnGestionRutas.setForeground(new java.awt.Color(0, 102, 102));
        BtnGestionRutas.setText("Gestionar Rutas");
        BtnGestionRutas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BtnGestionRutas.setContentAreaFilled(false);
        BtnGestionRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionRutasActionPerformed(evt);
            }
        });

        BtnGestionChoferes.setBackground(new java.awt.Color(243, 249, 249));
        BtnGestionChoferes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnGestionChoferes.setForeground(new java.awt.Color(0, 102, 102));
        BtnGestionChoferes.setText("Gestión Choferes");
        BtnGestionChoferes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BtnGestionChoferes.setContentAreaFilled(false);
        BtnGestionChoferes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGestionChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionChoferesActionPerformed(evt);
            }
        });

        BtnAdministrador.setBackground(new java.awt.Color(243, 249, 249));
        BtnAdministrador.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnAdministrador.setForeground(new java.awt.Color(0, 102, 102));
        BtnAdministrador.setText("Administradores");
        BtnAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BtnAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdministradorActionPerformed(evt);
            }
        });

        BtnCerrarSesion.setBackground(new java.awt.Color(137, 8, 8));
        BtnCerrarSesion.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        BtnCerrarSesion.setForeground(new java.awt.Color(137, 8, 8));
        BtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sesion.png"))); // NOI18N
        BtnCerrarSesion.setContentAreaFilled(false);
        BtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCerrarSesion.setFocusPainted(false);
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        BtnIterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/refresco.png"))); // NOI18N
        BtnIterar.setBorderPainted(false);
        BtnIterar.setContentAreaFilled(false);
        BtnIterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIterarActionPerformed(evt);
            }
        });

        BtnGestionViajes.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnGestionViajes.setForeground(new java.awt.Color(0, 102, 102));
        BtnGestionViajes.setText("Gestión Viajes");
        BtnGestionViajes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BtnGestionViajes.setContentAreaFilled(false);
        BtnGestionViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnGestionViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestionViajesActionPerformed(evt);
            }
        });

        BtnVentaTickets.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BtnVentaTickets.setForeground(new java.awt.Color(0, 102, 102));
        BtnVentaTickets.setText("Venta de Tickets");
        BtnVentaTickets.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        BtnVentaTickets.setContentAreaFilled(false);
        BtnVentaTickets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVentaTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentaTicketsActionPerformed(evt);
            }
        });

        JTableGeneral.setBackground(new java.awt.Color(243, 249, 249));
        JTableGeneral.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        JTableGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Viaje", "Nombre Chofer", "Nombre Ruta", "Fecha de Viaje", "Hora"
            }
        ));
        JTableGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JTableGeneral.setDropMode(javax.swing.DropMode.ON);
        JTableGeneral.setGridColor(new java.awt.Color(243, 249, 249));
        JTableGeneral.setSelectionBackground(new java.awt.Color(51, 51, 51));
        JTableGeneral.setSelectionForeground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(JTableGeneral);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(77, 77, 77)
                .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnGestionRutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnGestionChoferes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnGestionFlotilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnIterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(BtnGestionViajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96)
                        .addComponent(BtnVentaTickets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))
                        .addGap(15, 15, 15)))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGestionViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGestionFlotilla, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIterar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnVentaTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnGestionRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(BtnGestionChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(BtnAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGestionChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionChoferesActionPerformed
        JDialogGestionChoferes jdChoferes = new JDialogGestionChoferes(this, true);
        jdChoferes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnGestionChoferesActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        JFrameLogin login = new JFrameLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void BtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdministradorActionPerformed
        JDialogAdministradores jdAdmi = new JDialogAdministradores(this, true);
        jdAdmi.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAdministradorActionPerformed

    private void BtnGestionRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionRutasActionPerformed
        JDialogGestionRutas jdRutas = new JDialogGestionRutas(this, true);
        jdRutas.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnGestionRutasActionPerformed

    private void BtnGestionFlotillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionFlotillaActionPerformed
        JDialogGestionFlotilla jdFlotilla = new JDialogGestionFlotilla(this, true);
        jdFlotilla.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnGestionFlotillaActionPerformed

    private void BtnGestionViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestionViajesActionPerformed
        JDialogGestionViajes jdViajes = new JDialogGestionViajes(this, true);
        jdViajes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnGestionViajesActionPerformed

    private void BtnIterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIterarActionPerformed
        ShowTableGestionViaje();
    }//GEN-LAST:event_BtnIterarActionPerformed

    private void BtnVentaTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentaTicketsActionPerformed
        JDialogVentaTicket jdTicket = new JDialogVentaTicket(this, true);
        jdTicket.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVentaTicketsActionPerformed
     public void Cargardata()
    {
    
        ListaGesVia = ContextTXTGestionViajes.LeerDatos();
    
    }
    public void ShowTableGestionViaje() {
        String GestViaje[][] = new String[ListaGesVia.size()][5];

        for (int i = 0; i < ListaGesVia.size(); i++) {
            GestViaje[i][0] = ListaGesVia.get(i).getIdViaje();
            GestViaje[i][1] = ListaGesVia.get(i).getCedulaChofer();
            GestViaje[i][2] = ListaGesVia.get(i).getIdRuta();
            GestViaje[i][3] = ListaGesVia.get(i).getFecha();
            GestViaje[i][4] = ListaGesVia.get(i).getHora();
        }

        JTableGeneral.setModel(new javax.swing.table.DefaultTableModel(GestViaje, new String[]{"Id Viaje", "Cedula", "Fecha", "Hora"}));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSISBUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSISBUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSISBUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSISBUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSISBUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdministrador;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnGestionChoferes;
    private javax.swing.JButton BtnGestionFlotilla;
    private javax.swing.JButton BtnGestionRutas;
    private javax.swing.JButton BtnGestionViajes;
    private javax.swing.JButton BtnIterar;
    private javax.swing.JButton BtnVentaTickets;
    private javax.swing.JTable JTableGeneral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
